Fix linting errors
SolidLabResearch/solid-stream-aggregator pull request #32
Opened 2024-02-19 15:09 UTC by argahsuknesib

I fixed the linting issues in the repository. The unit tests are still a work in progress which I will fix and add with another pull request after the linting errors are reviewed.

Running the command,
```bash
npm run lint:ts
```
currently gives, 
```bash
✖ 267 problems (0 errors, 267 warnings)
```
The warnings are documentation warnings with JSDoc which aren't important to resolve at the current moment (please correct me on this) and will be resolved in future.

2024-02-19 15:31 UTC, pheyvaer requested changes
The folder `.idea` is personal to your setup and doesn't belong in the repo.

2024-02-19 15:33 UTC, argahsuknesib commented
Thanks for pointing it out @pheyvaer, I changed the IDE but forgot to add the personal setup of the IDE into the .gitignore file.

2024-02-20 12:44 UTC, pheyvaer commented
> The warnings are documentation warnings with JSDoc which aren't important to resolve at the current moment (please correct me on this) and will be resolved in future.

The documentation is the main reason why I added linting 😄  So yes they have to be fixed.

2024-02-20 15:00 UTC, argahsuknesib commented
Running,
```bash
npm run lint:ts
```
will give no errors or warnings now.

2024-02-20 17:46 UTC, pheyvaer commented
@argahsuknesib We also need to docs for the classes and their methods. Can you fix that as well? I updated the lint config for that.

2024-02-20 18:16 UTC, argahsuknesib commented
I got another 126 JSDoc comment warnings, I will get rid of the warnings with another commit and reassign you to review. Thanks @pheyvaer !

2024-02-21 07:10 UTC, pheyvaer requested changes

2024-02-21 07:10 UTC, pheyvaer commented
> I got another 126 JSDoc comment warnings, I will get rid of the warnings with another commit and reassign you to review. Thanks @pheyvaer !

Ok, great! I also added some minor comments of things that I noticed.

2024-02-21 10:07 UTC, argahsuknesib commented on logs/aggregation.log
I will add them to .gitignore

2024-02-21 10:08 UTC, argahsuknesib commented on scratch/test.ts
The scratch files are created by me, in which I test some code. But they don't belong in the repo and I added them to .gitignore.

2024-02-21 10:09 UTC, argahsuknesib commented on src/service/query-registry/QueryRegistry.test.ts
> +    it('delete_all_queries_from_the_registry', async () => {
ok thanks, will do.

2024-02-21 10:32 UTC, argahsuknesib commented on src/server/HTTPServer.ts
>                  // TODO : bug that the notification is sent more than once from the solid server.
It is not, I will add it into the issues.

2024-02-22 07:42 UTC, argahsuknesib commented
I am working on the tests right now @pheyvaer, should I re-request a review when the coverage is 100%?

2024-02-22 09:16 UTC, pheyvaer commented
> I am working on the tests right now @pheyvaer, should I re-request a review when the coverage is 100%? (as the linting errors are fixed now)

This PR is only for linting errors. So if you are changing/adding tests then this should happen in a separate branch. The linting errors for the tests that are already in this PR should be covered yes.

2024-02-22 13:10 UTC, pheyvaer commented on src/utils/ldes-in-ldp/EventSource.ts
> +        // TODO : check for headers, as well as error handling. check if you can increase the timeout for the get request as some resources might take longer to load (due to large files, slow server,
Can you add issue for this as well?

2024-02-22 13:21 UTC, argahsuknesib commented on src/utils/ldes-in-ldp/EventSource.ts
> +        // TODO : check for headers, as well as error handling. check if you can increase the timeout for the get request as some resources might take longer to load (due to large files, slow server,
done for this as well.

2024-02-22 13:21 UTC, argahsuknesib commented on src/service/aggregator/AggregatorInstantiator.ts
>      // TODO : add extra projection variables to the aggregation event.
done

2024-02-22 13:43 UTC, pheyvaer approved these changes

2024-02-22 13:44 UTC, merged